name: C/C++ CI

on:
  push:
    branches: [ master ] 
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Run -f generalMakefile
        env:
          TOKEN: ${{ secrets.TOKEN }}
        run: make -f generalMakefile all
